# Generated by Django 4.2.4 on 2024-09-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('mail', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('apodo', models.CharField(max_length=200, verbose_name='Apodo')),
            ],
        ),
    ]
