# Generated by Django 4.2.4 on 2024-09-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_usuarios_options_usuarios_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
