# Generated by Django 4.2.4 on 2024-09-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_usuarios_created_alter_usuarios_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, max_length=200, verbose_name='rol'),
        ),
    ]
