# Generated by Django 4.2.4 on 2024-09-23 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usuarios_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='disponibilidad',
            field=models.BooleanField(default=True, verbose_name='Disponibilidad'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='estado',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='honor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Honor'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='rol',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rol'),
        ),
    ]
