# Generated by Django 4.2.4 on 2024-09-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuarios_disponibilidad_usuarios_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='honor',
            field=models.IntegerField(blank=True, default=100, null=True, verbose_name='Honor'),
        ),
    ]
