# Generated by Django 5.0 on 2024-10-02 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_alter_usuarios_honor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medallas',
            fields=[
                ('medalla_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_medalla', models.CharField(max_length=60, verbose_name='Nombre')),
                ('desc_medalla', models.CharField(max_length=250, verbose_name='Descripción')),
                ('image_medalla', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
                ('puntos_por_nivel', models.IntegerField(default=4, verbose_name='Puntos por Nivel')),
                ('nivel_maximo', models.IntegerField(default=25, verbose_name='Nivel Máximo')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medalla',
                'verbose_name_plural': 'Medallas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Titulos',
            fields=[
                ('titulo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_titulo', models.CharField(max_length=60, verbose_name='Nombre')),
                ('desc_titulo', models.CharField(max_length=250, verbose_name='Descripción')),
                ('image_titulo', models.ImageField(null=True, upload_to='', verbose_name='Logo')),
                ('es_positivo', models.BooleanField(default=True, verbose_name='¿Es positivo?')),
                ('es_exclusivo', models.BooleanField(default=True, verbose_name='¿Es exclusivo?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Titulo',
                'verbose_name_plural': 'Titulos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='MedallasPorPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_experiencia', models.IntegerField(default=0, verbose_name='Puntos XP')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('medalla_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimientos.medallas', verbose_name='Medalla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'MedallaPorPersona',
                'verbose_name_plural': 'MedallasPorPersona',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='TitulosPorPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(blank=True, null=True, verbose_name='Fecha de asignación')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('titulo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconocimientos.titulos', verbose_name='Título')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios', verbose_name='Usuarios')),
            ],
            options={
                'verbose_name': 'TituloPorPersona',
                'verbose_name_plural': 'TitulosPorPersona',
                'ordering': ['-created'],
            },
        ),
    ]
